#pragma once

// define all actions, directly mapped to led shift register pins (can't be more optimized :) )

#define SRV_1 9
#define SRV_2 8
#define SRV_3 11
#define SRV_4 10

#define FIGHTER_ATTACK 12
#define FIGHTER_DEFEND 13
#define FIGHTER_HOLDFIRE 14
#define FIGHTER_HOLDPOS 15
#define FIGHTER_DOCK 0
#define FIGHTER_FOLLOW 1
#define FIGHTER_FIREATWILL 2

#define WING_TARGET 4
#define WING_1 3
#define WING_2 5
#define WING_NAVLOCK 6
#define WING_3 7

#define STARNAV_GALAXY_MAP 21
#define STARNAV_SYSTEM_MAP 18
#define STARNAV_NEXT_SYSTEM 29

#define DEFENSE_SHIELD_CELL 22
#define DEFENSE_HEAT_SINK 19
#define DEFENSE_CHAFF 16
#define DEFENSE_ECM 30

#define ENERGY_SYSTEMS 23
#define ENERGY_ENGINE 20
#define ENERGY_WEAPONS 17
#define ENERGY_BALANCE 31

#define COCKPIT_MODE 37

#define TARGETING_MOST_HOSTILE 38
#define TARGETING_MAIN_THREAT 34
#define TARGETING_PREVIOUS_THREAT 47
#define TARGETING_NEXT_THREAT 43
#define TARGETING_NEXT_TARGET 35
#define TARGETING_NEXT_SUBSYS 32
#define TARGETING_NEXT_GROUP 44

#define ENGINE_CRUISE 39
#define ENGINE_JUMP 36
#define ENGINE_DISENGAGE 33
#define ENGINE_FULL_STOP 45

#define SHIP_SILENT_RUNNING 64
#define SHIP_JETTISON_CARGO 65
#define SHIP_EMERGENCY_STOP 66
#define SHIP_CARGO_SCOOP 67
#define SHIP_LIGHTS 68
#define SHIP_HARDPOINTS 69
#define SHIP_LANDING_GEARS 70
#define SHIP_FLIGHT_ASSIST 71

#define SCANNER_DSD 72
#define SCANNER_PREVIOUS_FILTER 46
#define SCANNER_NEXT_FILTER 42

#define SCANNER_ACS 73
#define SCANNER_ZOOM_LEFT 74
#define SCANNER_ZOOM_RIGHT 75
#define SCANNER_ZOOM_CLICK 76
#define SCANNER_FREQ_LEFT 77
#define SCANNER_FREQ_RIGHT 78
#define SCANNER_FREQ_TARGET 79

#define TARGETING_SENSORS_LEFT 80
#define TARGETING_SENSORS_RIGHT 81
//#define TARGETING_SENSORS_CLICK 82

